#!/usr/bin/env python3
"""Run the VeeR EL2 core's own configuration generator.

`rtl/core/veer_el2/configs/veer.config` is a Perl script shipped with the core.
It turns a hash of core options into the include files the RTL needs
(`common_defines.vh`, `el2_pdef.vh`, `el2_param.vh`, `pic_map_auto.svh`).

This wrapper

  * reads the options from `config/soc_config.yaml` (single source of truth --
    the options are **not** duplicated here),
  * runs the upstream generator into a build directory, and
  * copies only the include files the RTL needs into `sim/gen/veer/`, together
    with a copy of the exact command line so a run is reproducible.

Nothing in the core tree is modified.

Usage:  python3 tools/gen_veer_config.py [--print]
"""

from __future__ import print_function

import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)

from soc_config import load_config, ConfigError  # noqa: E402

# Files the core's RTL includes.  `defines.h`, `whisper.json`, `perl_configs.pl`
# and the upstream `link.ld` are produced for flows this project does not use.
WANTED = ["common_defines.vh", "el2_pdef.vh", "el2_param.vh", "pic_map_auto.svh"]


def build_options(cfg):
    opts = ["reset_vec=0x%08x" % cfg.reset_vector]
    for key in sorted(cfg.veer_options):
        opts.append("%s=%s" % (key, cfg.veer_options[key]))
    return opts


def run(verbose=False):
    cfg = load_config(os.path.join(ROOT, "config", "soc_config.yaml"))
    core_root = os.path.join(ROOT, cfg.core_rtl_dir)
    script = os.path.join(core_root, "configs", "veer.config")
    if not os.path.isfile(script):
        raise ConfigError("VeeR core not found at %s" % core_root)

    workdir = os.path.join(ROOT, "sim", "build", "veer")
    outdir = os.path.join(ROOT, "sim", "gen", "veer")
    for path in (workdir, outdir):
        if not os.path.isdir(path):
            os.makedirs(path)

    opts = build_options(cfg)
    cmd = ["perl", script] + ["-set=%s" % opt for opt in opts]
    env = os.environ.copy()
    env["RV_ROOT"] = core_root
    env["BUILD_PATH"] = workdir

    if verbose:
        print("veer-config: %s" % " ".join(cmd))

    proc = subprocess.Popen(cmd, cwd=core_root, env=env,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = proc.communicate()[0].decode("utf-8", "replace")
    if proc.returncode != 0:
        sys.stderr.write(output)
        raise ConfigError("VeeR configuration generator failed (exit %d)" % proc.returncode)

    copied = []
    for name in WANTED:
        src = os.path.join(workdir, name)
        if not os.path.isfile(src):
            raise ConfigError("VeeR generator did not produce %s" % name)
        dst = os.path.join(outdir, name)
        shutil.copyfile(src, dst)
        copied.append(dst)

    # record exactly what was run, so a build is reproducible and auditable
    record = os.path.join(outdir, "veer_config.cmd")
    with open(record, "w") as handle:
        handle.write("# generated by tools/gen_veer_config.py -- do not edit\n")
        handle.write("RV_ROOT=%s\n" % core_root)
        handle.write("BUILD_PATH=%s\n" % workdir)
        handle.write("perl configs/veer.config %s\n"
                     % " ".join("-set=%s" % opt for opt in opts))
    copied.append(record)
    return copied


def main(argv):
    verbose = "--print" in argv
    try:
        copied = run(verbose=verbose)
    except ConfigError as exc:
        sys.stderr.write("gen_veer_config: %s\n" % exc)
        return 1
    print("gen_veer_config: %d file(s)" % len(copied))
    for path in copied:
        print("      %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
